<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/5/10
 * Time: 15:16
 */

class HouseCorp extends Corp
{
    private $house;

    public function __construct(House $house)
    {
        $this->house = $house;
    }

    public function makeMoney()
    {
        parent::makeMoney(); // TODO: Change the autogenerated stub
        echo "房地产公司赚大钱了~";
    }


}