<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/5/10
 * Time: 15:16
 */

class ShanZhaiCorp extends Corp
{
    private $shanzhai;

    public function __construct(ProductBridge $IPod)
    {
        $this->shanzhai = $IPod;
    }

    public function makeMoney()
    {
        parent::makeMoney(); // TODO: Change the autogenerated stub
        echo "山寨公司的产品赚小钱了~";
    }

}