<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/5/16
 * Time: 12:16
 */

class ChinaDnsServer extends DnsServer
{
    protected function getsRecoder($str_domain)
    {
        $recoder =  parent::getsRecoder($str_domain); // TODO: Change the autogenerated stub
        $recoder->setOwner("中国顶级域名解析服务器");
        return $recoder;
    }
    protected function isLocal($str_domain)
    {
        // TODO: Implement isLocal() method.
        return $str_domain.".cn";
    }

}